### ISSUE TITLE
how to fix? also how to load command book

### ISSUE THREAD

**Issue by yuiiaaz** [tanjeffreyz/auto-maple#60]
[~] Loading routine '':
[!] File path not provided, no routine was previously loaded either.

[~] Loading routine '':
[!] File path not provided, no routine was previously loaded either.

**Comment by tanjeffreyz** [comment]
Hi, before you can run a routine, you need to go to "File > Load Command Book" and load a command book file. Then, you can click "File > Load Routine" to load a routine. A routine cannot be loaded if no command book is active, since Auto Maple won't know how to interpret the commands in the routine file.
