### ISSUE TITLE
Miss enetring portal

### ISSUE THREAD

**Issue by nehcap** [tanjeffreyz/auto-maple#96]
Sometime the kanna tries to up teleport on portal 
So if you can fix it please by adding rope lift bind ty:)

**Comment by tanjeffreyz** [comment]
Hi, this should be fixed in the future, but in the meantime try using `jump=True` for Kanna's up-teleport:

![image](https://user-images.githubusercontent.com/69165598/170852161-d4ea5d67-600b-4a81-9276-592fc864ceb7.png)

It's programmed to jump before pressing the up arrow, so you won't enter the portal
